name: riverpod_testing
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  pretty_dio_logger: ^1.4.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^4.0.0+1
  build_runner: ^2.7.1

flutter:
  uses-material-design: true
